# yaml-language-server: $schema=https://json.schemastore.org/pyproject.json
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sql-learning-materials"
version = "0.0.0"
description = "SQL scripts that demonstrate various features and concepts."
authors = [{name = "billwallis"}]
readme = "README.md"
license-files = ["LICENSE"]
keywords = ["sql", "sql-server", "postgres", "sqlite", "duckdb"]
urls = {Repository = "https://github.com/billwallis/sql-learning-materials"}
requires-python = ">=3.13"
dependencies = [
    "db-query-profiler>=0.0.6",
    "duckdb>=1.5.3",
    # PostgreSQL driver
    "psycopg2>=2.9.9; sys_platform == 'win32'",
    "psycopg2-binary>=2.9.9; sys_platform == 'darwin'",
    # SQL Server driver
    "pyodbc>=5.1.0",
]

[dependency-groups]
dev = [
    "poethepoet>=0.46.0",
    "pre-commit>=4.6.0",
]
test = [
    "covdefaults>=2.3.0",
    "coverage>=7.13.5",
    "pytest>=9.0.3",
]
docs = [
    "markdown-callouts>=0.4.0",
    "mdx-truly-sane-lists>=1.3",
    "mkdocs>=1.6.1",
    "mkdocs-callouts>=1.16.0",
    "mkdocs-material>=9.6.7",
]


[tool.poe]
verbosity = -1
envfile.optional = ".env"

[tool.poe.tasks]
install.shell = """
    pip install --editable . --group dev --group test --group docs
    pre-commit install --install-hooks
"""
test.shell = """
    coverage run -m pytest -vvv
    coverage report --no-skip-covered --include 'src/*'
    coverage report --no-skip-covered --include 'tests/*'
    coverage xml --quiet
"""

[tool.poe.tasks.lint]
control.expr = "sys.platform"

[[tool.poe.tasks.lint.switch]]
case = "win32"
shell = """
    echo '=== pre-commit checks ==='
    SKIP=identity pre-commit run --all-files --hook-stage pre-commit
    echo '=== pre-push checks ==='
    SKIP=identity pre-commit run --all-files --hook-stage pre-push
"""

[[tool.poe.tasks.lint.switch]]
shell = """
    echo '\\033[0;34mpre-commit checks\\033[0m'
    SKIP=identity pre-commit run --all-files --hook-stage pre-commit
    echo '\\033[0;34mpre-push checks\\033[0m'
    SKIP=identity pre-commit run --all-files --hook-stage pre-push
"""


[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.coverage]
run.source = ["src", "tests"]
run.plugins = ["covdefaults"]  # https://youtu.be/70T6OxKwxm0
report.fail_under = 80
report.exclude_lines = [
    "@pytest.mark.skip",
    "@pytest.mark.xfail",
]
